# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-03-04 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255, null=True, unique=True, verbose_name='email')),
                ('is_active', models.NullBooleanField(default=True, verbose_name='Validated')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Phone Number/Email')),
                ('first_name', models.CharField(blank=True, default=uuid.uuid4, max_length=255, verbose_name='Validated')),
                ('middle_name', models.CharField(blank=True, default=uuid.uuid4, max_length=255, verbose_name='Validated')),
                ('last_name', models.CharField(blank=True, default=uuid.uuid4, max_length=255, verbose_name='Validated')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
